-- ============================================
-- Git-Related Quiz Questions
-- ============================================
-- Insert these questions into the quiz_questions table

INSERT INTO quiz_questions (question, options, correct_answer, category, difficulty, explanation) VALUES

-- Basic Git Concepts
('What is Git?', 
 '["A version control system", "A programming language", "A database", "A web framework"]', 
 0, 
 'git', 
 'easy',
 'Git is a distributed version control system designed to track changes in source code during software development.'),

('What does "git clone" do?', 
 '["Creates a new repository", "Copies a remote repository to your local machine", "Deletes a repository", "Merges two branches"]', 
 1, 
 'git', 
 'easy',
 'git clone creates a copy of a remote repository on your local machine, including all branches and commit history.'),

('What is a commit in Git?', 
 '["A branch", "A snapshot of changes at a point in time", "A merge operation", "A remote repository"]', 
 1, 
 'git', 
 'easy',
 'A commit is a snapshot of your repository at a specific point in time, containing changes to files and a commit message.'),

('What is the default branch name in Git?', 
 '["develop", "main", "master", "Both main and master are common defaults"]', 
 3, 
 'git', 
 'easy',
 'Historically "master" was the default, but "main" has become the modern standard. Both are common defaults depending on Git version and configuration.'),

-- Git Commands
('What does "git add" do?', 
 '["Commits changes", "Stages changes for commit", "Creates a new branch", "Pushes to remote"]', 
 1, 
 'git', 
 'easy',
 'git add stages changes in your working directory, preparing them to be included in the next commit.'),

('What is the command to see your commit history?', 
 '["git history", "git log", "git show", "git commits"]', 
 1, 
 'git', 
 'easy',
 'git log displays the commit history, showing commits, authors, dates, and messages.'),

('What does "git status" show?', 
 '["All commits", "The current branch", "The state of your working directory and staging area", "Remote repositories"]', 
 2, 
 'git', 
 'easy',
 'git status shows which files have been modified, staged, or are untracked in your working directory.'),

('What command discards changes in your working directory?', 
 '["git remove", "git discard", "git reset", "git checkout -- <file> or git restore"]', 
 3, 
 'git', 
 'medium',
 'git checkout -- <file> or git restore <file> discards changes in the working directory, reverting to the last committed version.'),

('What does "git pull" do?', 
 '["Pushes changes to remote", "Fetches and merges changes from remote", "Creates a new branch", "Deletes a branch"]', 
 1, 
 'git', 
 'medium',
 'git pull fetches changes from the remote repository and merges them into your current branch.'),

('What is the difference between "git fetch" and "git pull"?', 
 '["They are the same", "git fetch downloads changes, git pull downloads and merges", "git pull downloads, git fetch merges", "git fetch is deprecated"]', 
 1, 
 'git', 
 'medium',
 'git fetch downloads changes from remote without merging, while git pull downloads and automatically merges into your current branch.'),

-- Branching
('What is a branch in Git?', 
 '["A copy of the repository", "A pointer to a specific commit", "A remote repository", "A commit message"]', 
 1, 
 'git', 
 'easy',
 'A branch is a movable pointer to a specific commit, allowing you to work on different features independently.'),

('What command creates a new branch?', 
 '["git new branch", "git branch <name>", "git create branch", "git add branch"]', 
 1, 
 'git', 
 'easy',
 'git branch <name> creates a new branch. Use git checkout -b <name> or git switch -c <name> to create and switch to it.'),

('What does "git merge" do?', 
 '["Deletes a branch", "Combines changes from one branch into another", "Creates a new branch", "Pushes to remote"]', 
 1, 
 'git', 
 'medium',
 'git merge combines changes from one branch into another, creating a merge commit if needed.'),

('What is a merge conflict?', 
 '["When Git cannot merge branches automatically", "When two branches have conflicting changes to the same file", "When a branch is deleted", "When pushing fails"]', 
 1, 
 'git', 
 'medium',
 'A merge conflict occurs when Git cannot automatically merge changes because both branches modified the same part of a file.'),

('What is a fast-forward merge?', 
 '["A merge that requires conflict resolution", "A merge where the branch pointer moves forward without creating a merge commit", "A merge that fails", "A merge between remote branches"]', 
 1, 
 'git', 
 'medium',
 'A fast-forward merge happens when the target branch has no new commits, so Git simply moves the pointer forward without creating a merge commit.'),

-- Remote Repositories
('What is a remote in Git?', 
 '["A branch", "A reference to a repository on another server", "A commit", "A merge"]', 
 1, 
 'git', 
 'easy',
 'A remote is a reference to a repository stored on another server, typically used for collaboration.'),

('What does "git push" do?', 
 '["Downloads changes from remote", "Uploads local commits to remote repository", "Creates a new branch", "Merges branches"]', 
 1, 
 'git', 
 'easy',
 'git push uploads your local commits to the remote repository, making them available to others.'),

('What is the default name for the main remote repository?', 
 '["origin", "main", "master", "remote"]', 
 0, 
 'git', 
 'easy',
 '"origin" is the conventional default name for the main remote repository when you clone a repository.'),

-- Advanced Git
('What is a rebase in Git?', 
 '["A way to delete commits", "A way to move or combine commits to create a linear history", "A type of merge", "A remote operation"]', 
 1, 
 'git', 
 'medium',
 'Rebasing moves or combines commits to create a linear history, rewriting commit history in the process.'),

('What is the difference between "git merge" and "git rebase"?', 
 '["They are identical", "Merge preserves history, rebase creates linear history", "Rebase preserves history, merge creates linear", "Merge is for branches, rebase is for commits"]', 
 1, 
 'git', 
 'medium',
 'Merge preserves the branching history with merge commits, while rebase creates a linear history by replaying commits.'),

('What is a detached HEAD state?', 
 '["When HEAD points to a specific commit instead of a branch", "When a branch is deleted", "When merge fails", "When repository is corrupted"]', 
 0, 
 'git', 
 'medium',
 'A detached HEAD occurs when you checkout a specific commit instead of a branch, meaning new commits won\'t belong to any branch.'),

('What does "git stash" do?', 
 '["Deletes changes", "Temporarily saves uncommitted changes", "Commits changes", "Pushes changes"]', 
 1, 
 'git', 
 'medium',
 'git stash temporarily saves uncommitted changes so you can switch branches or pull updates, then reapply them later.'),

('What is the ".gitignore" file used for?', 
 '["To ignore remote repositories", "To specify files Git should not track", "To configure Git settings", "To store commit messages"]', 
 1, 
 'git', 
 'easy',
 '.gitignore tells Git which files and directories to ignore, preventing them from being tracked or committed.'),

('What does "git diff" show?', 
 '["All commits", "Differences between commits, branches, or working directory", "Remote repositories", "Branch names"]', 
 1, 
 'git', 
 'medium',
 'git diff shows the differences between commits, branches, or your working directory and the staging area.'),

('What is a tag in Git?', 
 '["A branch", "A label pointing to a specific commit, often used for releases", "A merge commit", "A remote repository"]', 
 1, 
 'git', 
 'medium',
 'A tag is a label that points to a specific commit, commonly used to mark release versions (e.g., v1.0.0).'),

('What command creates a tag?', 
 '["git create tag", "git tag <name>", "git add tag", "git new tag"]', 
 1, 
 'git', 
 'medium',
 'git tag <name> creates a lightweight tag. Use git tag -a <name> -m "message" for an annotated tag.'),

('What does "git reset" do?', 
 '["Deletes the repository", "Moves the HEAD pointer to a different commit", "Pushes to remote", "Creates a branch"]', 
 1, 
 'git', 
 'medium',
 'git reset moves the HEAD pointer to a different commit, with options to also update the staging area and working directory.'),

('What is the difference between "git reset --soft" and "git reset --hard"?', 
 '["They are the same", "--soft keeps changes staged, --hard discards all changes", "--hard keeps changes, --soft discards", "Both discard changes"]', 
 1, 
 'git', 
 'hard',
 '--soft keeps changes staged for commit, while --hard discards all changes in both staging area and working directory.'),

('What does "git cherry-pick" do?', 
 '["Picks random commits", "Applies a specific commit from one branch to another", "Deletes commits", "Merges branches"]', 
 1, 
 'git', 
 'hard',
 'git cherry-pick applies a specific commit from one branch to another, creating a new commit with the same changes.'),

('What is a Git hook?', 
 '["A branch", "A script that runs automatically at certain Git events", "A commit message", "A remote repository"]', 
 1, 
 'git', 
 'hard',
 'Git hooks are scripts that run automatically at certain Git events, like before commits or after pushes, allowing automation.'),

('What does "git bisect" help you do?', 
 '["Merge branches", "Find the commit that introduced a bug", "Create branches", "Push to remote"]', 
 1, 
 'git', 
 'hard',
 'git bisect uses binary search to help you find the commit that introduced a bug by testing commits between known good and bad states.');
