-- ============================================
-- Quiz Questions: Git, Cloud, Data, AI (Beginners)
-- ============================================
-- Simple low-level questions for beginners

INSERT INTO quiz_questions (question, options, correct_answer, category, difficulty, explanation) VALUES

-- Git (beginner)
('What is Git?', 
 '["A version control system", "A programming language", "A database", "A web framework"]', 
 0, 
 'git', 
 'easy',
 'Git is a version control system used to track changes in files and coordinate work among people.'),

('What does "git clone" do?', 
 '["Creates a new repo", "Copies a remote repo to your computer", "Deletes a repo", "Merges two branches"]', 
 1, 
 'git', 
 'easy',
 'git clone downloads a copy of a repository from a remote server to your local machine.'),

('What is a commit in Git?', 
 '["A branch", "A saved snapshot of your changes", "A merge", "A remote"]', 
 1, 
 'git', 
 'easy',
 'A commit is a saved snapshot of your project at a point in time, with a message describing the change.'),

('What does "git add" do?', 
 '["Commits changes", "Stages files for the next commit", "Creates a branch", "Pushes to remote"]', 
 1, 
 'git', 
 'easy',
 'git add stages files so they will be included in your next commit.'),

('What does "git push" do?', 
 '["Downloads from remote", "Uploads your commits to the remote", "Creates a branch", "Merges branches"]', 
 1, 
 'git', 
 'easy',
 'git push sends your local commits to the remote repository so others can see them.'),

('What does "git status" show?', 
 '["All commits", "The current branch", "Which files are changed or staged", "Remote repos"]', 
 2, 
 'git', 
 'easy',
 'git status shows which files you have modified, staged, or that are untracked.'),

('What is the default remote name when you clone?', 
 '["origin", "main", "master", "remote"]', 
 0, 
 'git', 
 'easy',
 'When you clone a repo, Git names the remote "origin" by default.'),

('What is a branch in Git?', 
 '["A full copy of the repo", "A separate line of development", "A remote server", "A commit message"]', 
 1, 
 'git', 
 'easy',
 'A branch is a separate line of development so you can work on features without affecting the main code.'),

-- Cloud (beginner)
('What does "the cloud" mean in tech?', 
 '["Weather data", "Servers and services on the internet", "A type of software", "A programming language"]', 
 1, 
 'cloud', 
 'easy',
 'The cloud refers to servers and services that run on the internet instead of on your own computer.'),

('What is cloud computing?', 
 '["Using your laptop only", "Using internet-based servers to store and run apps", "A type of database", "A coding language"]', 
 1, 
 'cloud', 
 'easy',
 'Cloud computing means using remote servers on the internet to store data and run applications.'),

('What is SaaS?', 
 '["A type of hardware", "Software you use over the internet (as a service)", "A database", "A programming tool"]', 
 1, 
 'cloud', 
 'easy',
 'SaaS stands for Software as a Service—software you access over the internet, like Gmail or Netflix.'),

('What does "scalability" mean in cloud?', 
 '["How fast something runs", "Ability to grow or shrink resources as needed", "How secure it is", "The price"]', 
 1, 
 'cloud', 
 'easy',
 'Scalability means the system can handle more or less demand by adding or removing resources.'),

('What is a cloud provider?', 
 '["A person who uses the cloud", "A company that offers cloud services (e.g. AWS, Azure)", "A type of app", "A browser"]', 
 1, 
 'cloud', 
 'easy',
 'A cloud provider is a company that sells cloud services, like Amazon Web Services (AWS) or Microsoft Azure.'),

('What is "hosting" in the cloud?', 
 '["Downloading files", "Running your app or website on remote servers", "Writing code", "Backing up your PC"]', 
 1, 
 'cloud', 
 'easy',
 'Hosting means your app or website runs on servers owned by a cloud provider instead of your own machine.'),

-- Data (beginner)
('What is a database?', 
 '["A spreadsheet", "An organized store of data that can be queried", "A type of browser", "A programming language"]', 
 1, 
 'data', 
 'easy',
 'A database is a structured collection of data that can be stored, updated, and queried.'),

('What does "query" mean?', 
 '["To delete everything", "To ask for or retrieve specific data", "To backup data", "To format a disk"]', 
 1, 
 'data', 
 'easy',
 'A query is a request to get or change specific data from a database.'),

('What is a row in a database table?', 
 '["A column header", "One record or entry (e.g. one person)", "The table name", "A formula"]', 
 1, 
 'data', 
 'easy',
 'A row is one record in a table—for example, one customer or one product.'),

('What is a column in a database table?', 
 '["A row", "One type of information (e.g. name, age)", "The whole table", "A backup"]', 
 1, 
 'data', 
 'easy',
 'A column holds one type of information for all rows, like "email" or "age."'),

('What is SQL?', 
 '["A programming language for apps", "A language used to talk to databases", "A type of file", "A cloud service"]', 
 1, 
 'data', 
 'easy',
 'SQL (Structured Query Language) is used to create, read, update, and delete data in databases.'),

('What does "backup" mean for data?', 
 '["Deleting old data", "Making a copy of data for safety", "Sending data to the cloud", "Formatting data"]', 
 1, 
 'data', 
 'easy',
 'A backup is a copy of your data kept in case the original is lost or damaged.'),

('What is "structured data"?', 
 '["Random text", "Data in a fixed format (e.g. tables, fields)", "Encrypted data", "Deleted data"]', 
 1, 
 'data', 
 'easy',
 'Structured data is organized in a fixed format, like rows and columns in a database or spreadsheet.'),

-- AI (beginner)
('What does AI stand for?', 
 '["Automated Internet", "Artificial Intelligence", "Advanced Integration", "Application Interface"]', 
 1, 
 'ai', 
 'easy',
 'AI stands for Artificial Intelligence—software that can learn and perform tasks that usually need human thinking.'),

('What is machine learning?', 
 '["Typing on a keyboard", "Systems that learn from data without being explicitly programmed for every rule", "A type of database", "Cloud hosting"]', 
 1, 
 'ai', 
 'easy',
 'Machine learning is when a system learns patterns from data and can make decisions or predictions from that learning.'),

('What is a "model" in AI?', 
 '["A person who poses", "A program that has been trained on data to do a task", "A database table", "A type of server"]', 
 1, 
 'ai', 
 'easy',
 'In AI, a model is the result of training—a program that can make predictions or decisions based on what it learned.'),

('What does "training" mean in AI?', 
 '["Exercising", "Feeding data to a model so it learns patterns", "Installing software", "Backing up data"]', 
 1, 
 'ai', 
 'easy',
 'Training is the process of showing data to an AI model so it can learn and improve at a task.'),

('What is an example of AI you might use daily?', 
 '["A calculator app", "Voice assistant (e.g. Siri, Alexa)", "A text editor", "A file manager"]', 
 1, 
 'ai', 
 'easy',
 'Voice assistants, recommendations, and smart replies are everyday examples of AI.'),

('What is "data" in the context of AI?', 
 '["Only numbers", "Information used to train or run AI (text, numbers, images, etc.)", "Only images", "Only code"]', 
 1, 
 'ai', 
 'easy',
 'In AI, data is the information the system uses—could be text, numbers, images, or other inputs.'),

('What is a chatbot?', 
 '["A type of database", "A program that talks or chats with users, often using AI", "A cloud server", "A version control tool"]', 
 1, 
 'ai', 
 'easy',
 'A chatbot is a program that conducts a conversation with users, often powered by AI.');
